
version: '3.8'

services:
  eduguide-ai:
    build: .
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  # Optional: Add a simple database for demonstration
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: eduguide
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
